### ISSUE TITLE
Testnet 2

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-blockchain#12]
**Description**
Testnet 2 will reduce our block times for better demoability, and attempt to solve issues surrounding adding additional validators.  

**Tasks**
- [ ] Adjust block times
- [ ] #10 Use a better format for releases, like what we used for Meta 
- [ ] #4 Make adding validators easier to do

Any other information you want to share that is relevant to the issue. This might include the lines of code, screenshots, imagery, links, solutions, opinions, feedback, etc.
